# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.14.1
    hooks:
      - id: commitizen
  - repo: local
    hooks:
      - id: format
        name: Format code
        entry: bin/format.sh
        language: script
      - id: lint
        name: Lint code
        entry: bin/lint.sh
        language: script
