name: Run CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Get cache paths
        id: cache-paths
        run: echo "::set-output name=pip::$(pip cache dir)"

      - name: Pip cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.cache-paths.outputs.pip }}
          key: ${{ runner.os }}-pip-cache
          restore-keys: ${{ runner.os }}-pip-cache

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          pip install -r requirements-prod.txt -r requirements-test-prod.txt

      - name: Run checks
        run: |
          bin/format.sh
          bin/lint.sh

      - name: build
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          pip install --upgrade build
          python -m build

      - name: publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          pip install --upgrade twine
          python -m twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
